from __future__ import annotations

import json
from pathlib import Path
import sqlite3
import subprocess
import sys
import tempfile
import unittest

SKILL_ROOT = Path(__file__).resolve().parents[2]
CLI = SKILL_ROOT / "scripts" / "knowledge.py"


class DynamicViewsBlackBoxTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tempdir = tempfile.TemporaryDirectory()
        self.vault = Path(self.tempdir.name) / "Vault"
        self.knowledge = self.vault / "Knowledge"
        self.knowledge.mkdir(parents=True)
        self.seed = self.knowledge / "Existing.md"
        self.seed.write_text(
            "---\n"
            "topic: statistics\n"
            "custom: keep-me\n"
            "---\n"
            "# Existing\n\n"
            "Stable knowledge body.\n",
            encoding="utf-8",
        )
        self.run_cli(
            "register",
            "--vault", str(self.vault),
            "--scope", "Knowledge",
            "--note", "Knowledge/Existing.md",
            "--default-write-root", "Knowledge",
        )
        self.material = json.loads(
            self.run_cli(
                "capture",
                "--vault", str(self.vault),
                "--confirmed-intent",
                "--note", "Material body",
            ).stdout
        )

    def tearDown(self) -> None:
        self.tempdir.cleanup()

    @property
    def database(self) -> Path:
        return self.vault / ".akira-knowledge" / "knowledge.sqlite"

    @property
    def view_dir(self) -> Path:
        return self.vault / "Akira Knowledge Views"

    @property
    def view_file(self) -> Path:
        return self.view_dir / "Akira Knowledge.base"

    def run_cli(self, *args: str, expect: int = 0) -> subprocess.CompletedProcess[str]:
        result = subprocess.run(
            [sys.executable, str(CLI), *args],
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(
            expect,
            result.returncode,
            msg=f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}",
        )
        return result

    def authority_snapshot(self) -> dict[str, bytes]:
        return {
            path.relative_to(self.vault).as_posix(): path.read_bytes()
            for path in sorted(self.vault.rglob("*.md"))
        }

    def object_state(self) -> list[tuple[str, str, str, int, str]]:
        with sqlite3.connect(self.database) as conn:
            return conn.execute(
                "SELECT identity, kind, locator, revision, authority_fingerprint "
                "FROM objects ORDER BY identity"
            ).fetchall()

    def test_rebuild_creates_current_and_material_views_without_authority_changes(self) -> None:
        before_authority = self.authority_snapshot()
        before_objects = self.object_state()

        payload = json.loads(
            self.run_cli(
                "views-rebuild",
                "--vault", str(self.vault),
            ).stdout
        )

        self.assertTrue(payload["projection"])
        self.assertEqual("Akira Knowledge Views/Akira Knowledge.base", payload["view_file"])
        self.assertEqual(
            ["Current Knowledge", "Retired Knowledge", "Materials"],
            payload["views"],
        )

        text = self.view_file.read_text(encoding="utf-8")
        self.assertTrue(text.startswith("# Generated by Akira Knowledge. Rebuildable Projection.\n"))
        self.assertIn('note.akira_knowledge_kind == "knowledge_asset"', text)
        self.assertIn('note.akira_knowledge_kind == "material_record"', text)
        self.assertIn("note.akira_knowledge_status", text)
        self.assertIn("Retired Knowledge", text)
        self.assertIn('note.akira_knowledge_lifecycle == "retired"', text)
        self.assertIn(
            '!file.hasProperty("akira_knowledge_lifecycle") || '
            'note.akira_knowledge_lifecycle != "retired"',
            text,
        )

        marker = self.view_dir / ".akira-knowledge-projection"
        self.assertEqual("akira-knowledge-views:v1\n", marker.read_text(encoding="utf-8"))
        self.assertEqual(before_authority, self.authority_snapshot())
        self.assertEqual(before_objects, self.object_state())

    def test_deleted_or_corrupt_owned_view_is_rebuildable_without_revision_change(self) -> None:
        before_authority = self.authority_snapshot()
        before_objects = self.object_state()

        self.run_cli("views-rebuild", "--vault", str(self.vault))
        canonical = self.view_file.read_text(encoding="utf-8")

        self.view_file.unlink()
        self.run_cli("views-rebuild", "--vault", str(self.vault))
        self.assertEqual(canonical, self.view_file.read_text(encoding="utf-8"))

        self.view_file.write_text("broken projection\n", encoding="utf-8")
        self.run_cli("views-rebuild", "--vault", str(self.vault))
        self.assertEqual(canonical, self.view_file.read_text(encoding="utf-8"))

        self.assertEqual(before_authority, self.authority_snapshot())
        self.assertEqual(before_objects, self.object_state())

    def test_unowned_same_name_directory_fails_closed_without_touching_user_files(self) -> None:
        foreign_dir = self.view_dir
        foreign_dir.mkdir()
        foreign_file = foreign_dir / "User.base"
        foreign_file.write_text("user-owned\n", encoding="utf-8")
        before_authority = self.authority_snapshot()
        before_objects = self.object_state()

        result = self.run_cli(
            "views-rebuild",
            "--vault", str(self.vault),
            expect=2,
        )

        self.assertIn("Refusing to overwrite unowned view directory", result.stderr)
        self.assertEqual("user-owned\n", foreign_file.read_text(encoding="utf-8"))
        self.assertFalse(self.view_file.exists())
        self.assertEqual(before_authority, self.authority_snapshot())
        self.assertEqual(before_objects, self.object_state())


if __name__ == "__main__":
    unittest.main()
