from __future__ import annotations

from pathlib import Path
import re

from knowledge_core import storage
from knowledge_core.common import BootstrapError, _vault_root, _write_atomic
from knowledge_core.persistence import relations as relation_store
from knowledge_core.resolution import ResolvedObject, resolve_objects

GRAPH_DIR_NAME = "AK Graph"
LEGACY_GRAPH_DIR_NAMES = ("Akira Knowledge Graph",)
OWNERSHIP_MARKER_NAME = ".akira-knowledge-projection"
OWNERSHIP_MARKER = "akira-knowledge-relation-graph:v1\n"


def _node_filename(identity: str) -> str:
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", identity):
        raise BootstrapError(
            f"Relation identity cannot be represented as a Graph Projection filename: {identity}"
        )
    return f"relation-{identity}.md"


def _wikilink(obj: ResolvedObject) -> str:
    target = Path(obj.locator).with_suffix("").as_posix()
    return f"[[{target}]]"


def _endpoint_text(
    ref: str,
    *,
    registry_identities: set[str],
    objects: dict[str, ResolvedObject],
) -> str:
    if ref not in registry_identities:
        return f"external: `{ref}`"
    obj = objects.get(ref)
    if obj is None:
        raise BootstrapError(
            f"Local relation endpoint cannot resolve current canonical Markdown: {ref}"
        )
    return f"{_wikilink(obj)} (`{ref}`)"


def _escape_code(value: str) -> str:
    return value.replace("`", "\\`")


def _relation_node_text(
    *,
    relation,
    provenance_entries: list[str],
    registry_identities: set[str],
    objects: dict[str, ResolvedObject],
) -> str:
    lines = [
        "<!-- Generated by Akira Knowledge. Rebuildable Projection. -->",
        "",
        "# Relation",
        "",
        f"- Relation identity: `{relation.identity}`",
        f"- Type: `{_escape_code(relation.relation_type)}`",
        f"- Status: `{relation.status}`",
        f"- Revision: `{relation.revision}`",
        (
            "- Source: "
            + _endpoint_text(
                relation.source_ref,
                registry_identities=registry_identities,
                objects=objects,
            )
        ),
        (
            "- Target: "
            + _endpoint_text(
                relation.target_ref,
                registry_identities=registry_identities,
                objects=objects,
            )
        ),
        "",
        "## Provenance",
        "",
    ]
    for provenance in provenance_entries:
        lines.append(f"- `{_escape_code(provenance)}`")
    lines.append("")
    return "\n".join(lines)


def rebuild_relation_graph(vault: Path) -> dict[str, object]:
    root = _vault_root(vault)
    config = storage.read_config(root)
    if config is None:
        raise BootstrapError("Vault is not bootstrapped")
    if not storage.db_path(root).exists():
        raise BootstrapError("Knowledge structured Authority store is missing")

    conn = storage.connect(root)
    try:
        storage.initialize_schema(conn)
        conn.commit()
        objects = resolve_objects(root, conn)
        registry_identities = {
            record.identity for record in storage.list_objects(conn)
        }
        relations = relation_store.list_active_relation_records(conn)
        node_payloads: list[tuple[str, str]] = []
        for relation in relations:
            name = _node_filename(relation.identity)
            text = _relation_node_text(
                relation=relation,
                provenance_entries=relation_store.list_relation_provenance(
                    conn, relation.identity
                ),
                registry_identities=registry_identities,
                objects=objects,
            )
            node_payloads.append((name, text))
    finally:
        conn.close()

    graph_dir = root / GRAPH_DIR_NAME
    if not graph_dir.exists():
        for legacy_name in LEGACY_GRAPH_DIR_NAMES:
            legacy_dir = root / legacy_name
            if not legacy_dir.exists():
                continue
            legacy_marker = legacy_dir / OWNERSHIP_MARKER_NAME
            if (
                legacy_dir.is_dir()
                and legacy_marker.is_file()
            ):
                try:
                    legacy_marker_text = legacy_marker.read_text(encoding="utf-8")
                except (OSError, UnicodeError):
                    continue
                if legacy_marker_text != OWNERSHIP_MARKER:
                    continue
                try:
                    legacy_dir.rename(graph_dir)
                except OSError as exc:
                    raise BootstrapError(
                        f"Cannot migrate legacy graph Projection directory: {exc}"
                    ) from exc
                break

    marker = graph_dir / OWNERSHIP_MARKER_NAME

    if graph_dir.exists() and not graph_dir.is_dir():
        raise BootstrapError(
            f"Graph Projection path exists but is not a directory: {GRAPH_DIR_NAME}"
        )
    if graph_dir.exists():
        if not marker.exists() or not marker.is_file():
            raise BootstrapError(
                f"Refusing to overwrite unowned graph directory: {GRAPH_DIR_NAME}"
            )
        try:
            marker_text = marker.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            raise BootstrapError(f"Cannot read graph ownership marker: {exc}") from exc
        if marker_text != OWNERSHIP_MARKER:
            raise BootstrapError(
                f"Graph ownership marker is invalid: {GRAPH_DIR_NAME}/{OWNERSHIP_MARKER_NAME}"
            )
    else:
        graph_dir.mkdir()
        _write_atomic(marker, OWNERSHIP_MARKER)

    expected_names = {name for name, _text in node_payloads}
    for existing in graph_dir.glob("relation-*.md"):
        if existing.name not in expected_names:
            existing.unlink()

    node_files: list[str] = []
    for name, text in node_payloads:
        node = graph_dir / name
        _write_atomic(node, text)
        node_files.append(f"{GRAPH_DIR_NAME}/{name}")

    return {
        "vault": str(root),
        "projection_directory": GRAPH_DIR_NAME,
        "relation_count": len(node_payloads),
        "relation_nodes": node_files,
        "projection": True,
    }
