from __future__ import annotations

from pathlib import Path

from knowledge_core import storage
from knowledge_core.common import BootstrapError, _vault_root, _write_atomic
from knowledge_core.resolution import resolve_objects

VIEW_DIR_NAME = "AK Views"
LEGACY_VIEW_DIR_NAMES = ("Akira Knowledge Views",)
VIEW_FILE_NAME = "Akira Knowledge.base"
OWNERSHIP_MARKER_NAME = ".akira-knowledge-projection"
OWNERSHIP_MARKER = "akira-knowledge-views:v1\n"


def _base_text() -> str:
    return """# Generated by Akira Knowledge. Rebuildable Projection.
properties:
  file.name:
    displayName: Note
  note.akira_knowledge_status:
    displayName: Status
  note.akira_knowledge_lifecycle:
    displayName: Lifecycle
views:
  - type: table
    name: Current Knowledge
    filters:
      and:
        - 'note.akira_knowledge_kind == "knowledge_asset"'
        - '!file.hasProperty("akira_knowledge_lifecycle") || (note.akira_knowledge_lifecycle != "retired" && note.akira_knowledge_lifecycle != "superseded")'
    order:
      - file.name
  - type: table
    name: Retired Knowledge
    filters:
      and:
        - 'note.akira_knowledge_kind == "knowledge_asset"'
        - 'note.akira_knowledge_lifecycle == "retired"'
    order:
      - file.name
  - type: table
    name: Superseded Knowledge
    filters:
      and:
        - 'note.akira_knowledge_kind == "knowledge_asset"'
        - 'note.akira_knowledge_lifecycle == "superseded"'
    order:
      - file.name
  - type: table
    name: Materials
    filters:
      and:
        - 'note.akira_knowledge_kind == "material_record"'
    order:
      - file.name
      - note.akira_knowledge_status
"""


def rebuild_dynamic_views(vault: Path) -> dict[str, object]:
    root = _vault_root(vault)
    config = storage.read_config(root)
    if config is None:
        raise BootstrapError("Vault is not bootstrapped")
    if not storage.db_path(root).exists():
        raise BootstrapError("Knowledge structured Authority store is missing")

    conn = storage.connect(root)
    try:
        storage.initialize_schema(conn)
        conn.commit()
        resolve_objects(root, conn)
    finally:
        conn.close()

    view_dir = root / VIEW_DIR_NAME
    if not view_dir.exists():
        for legacy_name in LEGACY_VIEW_DIR_NAMES:
            legacy_dir = root / legacy_name
            if not legacy_dir.exists():
                continue
            legacy_marker = legacy_dir / OWNERSHIP_MARKER_NAME
            if (
                legacy_dir.is_dir()
                and legacy_marker.is_file()
            ):
                try:
                    legacy_marker_text = legacy_marker.read_text(encoding="utf-8")
                except (OSError, UnicodeError):
                    continue
                if legacy_marker_text != OWNERSHIP_MARKER:
                    continue
                try:
                    legacy_dir.rename(view_dir)
                except OSError as exc:
                    raise BootstrapError(
                        f"Cannot migrate legacy view Projection directory: {exc}"
                    ) from exc
                break

    marker = view_dir / OWNERSHIP_MARKER_NAME
    view_file = view_dir / VIEW_FILE_NAME

    if view_dir.exists() and not view_dir.is_dir():
        raise BootstrapError(
            f"View Projection path exists but is not a directory: {VIEW_DIR_NAME}"
        )
    if view_dir.exists():
        if not marker.exists() or not marker.is_file():
            raise BootstrapError(
                f"Refusing to overwrite unowned view directory: {VIEW_DIR_NAME}"
            )
        try:
            marker_text = marker.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            raise BootstrapError(f"Cannot read view ownership marker: {exc}") from exc
        if marker_text != OWNERSHIP_MARKER:
            raise BootstrapError(
                f"View ownership marker is invalid: {VIEW_DIR_NAME}/{OWNERSHIP_MARKER_NAME}"
            )
    else:
        view_dir.mkdir()
        _write_atomic(marker, OWNERSHIP_MARKER)

    _write_atomic(view_file, _base_text())

    return {
        "vault": str(root),
        "projection_directory": VIEW_DIR_NAME,
        "view_file": f"{VIEW_DIR_NAME}/{VIEW_FILE_NAME}",
        "views": [
            "Current Knowledge",
            "Retired Knowledge",
            "Superseded Knowledge",
            "Materials",
        ],
        "projection": True,
    }
